# Numpy 실습

> 다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. <br>
이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. <br>
이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요. <br>

In [1]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.

In [7]:
print(sales_data.mean(axis = 0))
print(sales_data.mean(axis = 0))
print(sales_data.mean(axis = 0))

[[104. 124. 150. 172. 152. 166.]
 [ 86. 103. 120. 134. 129. 131.]
 [ 76. 102. 126. 122. 110. 116.]]
[[104. 124. 150. 172. 152. 166.]
 [ 86. 103. 120. 134. 129. 131.]
 [ 76. 102. 126. 122. 110. 116.]]
[[104. 124. 150. 172. 152. 166.]
 [ 86. 103. 120. 134. 129. 131.]
 [ 76. 102. 126. 122. 110. 116.]]


2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.

3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.

4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.